#!/bin/bash
## tt-rss daemon
# chkconfig: 345 86 14
# description: tt-rss update daemon
# processname: tt-rss
 
# Source function library.
. /etc/init.d/functions
 
# Define some variables
TT_PATH="/var/www/tt-rss"
PHPBIN=/usr/bin/php
UPDATESCRIPT="$TT_PATH/update_daemon2.php"
LOGFILE=/var/log/tt-rss-update.log
ERRLOGFILE=/var/log/tt-rss-update-error.log
USER=apache
 
NAME=tt-rss-updater
DESC="tt-rss update daemon"
PIDFILE=/var/run/$NAME.pid

start() {
  echo -n $"Starting $NAME"
  daemonize -u $USER -p $PIDFILE -o $LOGFILE -e $ERRLOGFILE -c $TT_PATH $PHPBIN $UPDATESCRIPT && success || failure 
	RETVAL=$?
  echo
	return $RETVAL
}

stop() {
  echo -n $"Stopping $NAME"
  killproc -p $PIDFILE $NAME
  RETVAL=$?
  echo
  return $RETVAL
}

rh_status() {
  status -p $PIDFILE $NAME
}

rh_status_q() {
	rh_status >/dev/null 2>&1
}

case "$1" in
  start)
		rh_status_q && echo $NAME is already running && exit 0
    start
    ;;

  status)
    rh_status
    ;;

  stop)
    stop
    ;;
 
  restart)
    stop
    start
    ;;
 
  *)
    echo "Usage: $0 {status|start|stop|restart}"
    exit 1
esac

